In [1]:
import numpy as np

In [2]:
# Buat matrix X ukuran 2x3
X = np.array([[1, 3, 5],
              [2, 4, 6]])

In [3]:
print("Matrix X:")
print(X)

Matrix X:
[[1 3 5]
 [2 4 6]]


In [4]:
# Tampilkan ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: (2, 3)


In [5]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])


Kolom pertama:
[1 2]


In [6]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])


Baris kedua:
[2 4 6]


ulangi soal nomor 1 menggunakan pytorch

In [7]:
import torch

In [8]:
# Buat matrix X ukuran 2x3
X = torch.tensor([[1, 3, 5],
                  [2, 4, 6]])

In [9]:
# Tampilkan matrix
print("Matrix X:")
print(X)

Matrix X:
tensor([[1, 3, 5],
        [2, 4, 6]])


In [10]:
# Tampilkan ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: torch.Size([2, 3])


In [11]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])


Kolom pertama:
tensor([1, 2])


In [12]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])


Baris kedua:
tensor([2, 4, 6])


ulangi soal nomor 1 menggunakan tensorflow

In [13]:
import tensorflow as tf

In [14]:
# Buat matrix X ukuran 2x3
X = tf.constant([[1, 3, 5],
                 [2, 4, 6]])

In [15]:
# Tampilkan matrix
print("Matrix X:")
print(X)

Matrix X:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [16]:
# Tampilkan ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: (2, 3)


In [17]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])


Kolom pertama:
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [18]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])


Baris kedua:
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
