In [1]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([17, 1, 60]) # type argument is optional, e.g.: dtype=np.float16
x

array([17,  1, 60])

In [4]:
# hitung panjang vector x
len(x)

3

In [5]:
# tampilkan ukuran vector x
x.shape

(3,)

In [6]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [7]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(17)

In [8]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

Vektor Transpose

In [9]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([17,  1, 60])

In [10]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [11]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[17, 1, 60]])
y

array([[17,  1, 60]])

In [12]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

Pytorch dan Tensorflow

In [13]:
import torch
import tensorflow as tf

In [14]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt = torch.tensor([17, 1, 60])
x_pt

tensor([17,  1, 60])

In [15]:
# tampilkan ukuran dari vector x_t
x_tf = tf.Variable([17, 1, 60])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([17,  1, 60], dtype=int32)>